name: yurl
title: "yURL"
summary: "A universal links & AASA file validator."
description: |
  yURL is a CLI (Command-Line Interface) and webapp that allows you to validate whether a URL is properly configured for Universal Links. This allows you to check if the apple-app-site-association (AASA) file exists and is in the proper format as defined by Apple.
license: MIT
base: core18
grade: stable
confinement: strict
adopt-info: yurl

parts:
  yurl:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build
      cp dist/yurl_linux_amd64/yurl $SNAPCRAFT_PART_INSTALL
      chmod +x $SNAPCRAFT_PART_INSTALL/yurl
      snapcraftctl set-version $(cat VERSION)

apps:
  yurl:
    command: yurl
    plugs:
      - home
      - network
